hw/xnest/xcb.c
os/connection.c

2^16 is 2 xor 16 which equals 18, not 2 to the power of 16 which is 65536

Fix incorrect power of two operator

---

Xi/exevents.c

Fixes this build error on arch linux:
```
../Xi/exevents.c:1394:26: error: array subscript ‘InternalEvent {aka union _InternalEvent}[0]’ is partly outside array bounds of ‘DeviceEvent[1]’ {aka ‘struct _DeviceEvent[1]’} [-Werror=array-bounds=]
1394 |                 evtype = GetXI2Type(ev->any.type);
|                          ^~~~~~~~~~~~~~~~~~~~~~~~
../Xi/exevents.c: In function ‘DeliverEmulatedMotionEvent’:
../Xi/exevents.c:1571:17: note: object ‘motion’ of size 432
1571 |     DeviceEvent motion;
|
```
which happens because of change in build options compared to master and gcc 15.1 in arch. I think this warning (and error) is a bug in gcc.
gcc 15.1 doesn't like when struct DeviceEvent is cast to union InternalEvent. InternalEvent has a union `any` type and `DeviceEvent` type and these …

Fix build on arch linux (cast between struct and union gcc error)

---

hw/xfree86/common/xf86Init.c
hw/xquartz/darwin.c
hw/xquartz/mach-startup/bundle-main.c

Might cause issues in some programs that check for the "X.Org X Server" string, but I'm not aware of any atm.

Rebrand 'X.Org X Server' to 'XLibre X Server'

---

hw/xnest/Events.c

Box.x2 and Box.y2 depend on Box.x1 and Box.y1. According to the C language, it has no guarantees in which order structures will be initialized, so this can lead to unspecified behavior

hw/xnest/Events: fix uninitialized BoxRec

---

README.md

this removes a duplicate entry and adds two missing ones
also, these repos aren't mirrored in x11libre org
xf86-video-armsoc
xf86-video-glint
xf86-video-impact
xf86-video-newport
xf86-video-opentegra
xf86-video-s3
xf86-video-tga
xf86-video-tseng
xf86-video-xgixp

fix drivers list in README

---

meson.build
meson_options.txt

Right now, meson is probing for and trying to enable systemd- as well as HAL-support automatically.
This is flawed in several ways:
a) the probing logic for systemd is broken (doesn't actually check for systemd, but just udev and dbus)
b) this should be deliberate decisions by the user/operator/distro, whether it's actually wanted
(just the presence of some libraries in the build environment alone doesn't tell it)
c) HAL is pretty much obsolete, so we're considering to drop it entirely 
--> anybody who still needs it: this is your wakeup call ;-)

meson_options: set defaults for systemd and HAL to false

---

dix/property.c

Does not affect work, but it is better to delete to debloat the codebase.
Compiled several times, no errors occurred.

dix: delete unused structure

---

xkb/xkb.c

This is a regression first caused by 182404fde6bcacf5e2f05424fde4073c96c2474e that sends back the old xkb data instead of the new one. This causes a mismatch in the data and size calculations between the XkbComputeGetMapReplySize that is called above that calculates the size of the reply and XkbAssembleMap that sets the data for the reply.
Without this fix this error is seen when running setxkbmap fr: "Error loading new keyboard description".
Fixes setxkbmap error described in #180

xkb: fix XkbGetKbdByName returning incorrect data

---

README.md

Since Alan Coopersmith (Sun/Oracle) currently attempting to sneak in subtle incompatibilities between Xlibre and Xorg drivers, it's time to set some ad hoc release tags of all the unreleased stuff, which are prefixed "xlibre-" and document them in the readme.

README.md: add driver release tags

---

randr/rrproviderproperty.c

If a device property is going to be updated, but failing due the new value being too big, the buffer isn't freed.
Also compacting the logic for this into small inline function.
Fixes: 948630fa428d8e0111c29a882c45b4c8bee5a796
Also needs to be applied to master.

randr: fix memleak in provider property update

---

miext/rootless/rootlessWindow.h

We're using XorgScreenWindowPositionParamRec here, so need to include that header.

rootless: fix missing include of dix/screen_hooks_priv.h

---

glamor/glamor_egl.c

This lets Zink take advantage of DRM modifiers on GPUs letting it properly handle the import of tiled buffers.
Should help out NVK users using XLibre.
(This is a copy of the FDO MR)

glamor: Enable dmabuf_capable for Zink

---

.github/workflows/build-xserver.yml

https://github.com/HaplessIdiot/xserver/security/code-scanning/16
This change adds permissions to build in read only to support ubuntu package standards. Fixes 2 CodeQL alerts with 2 lines.

.github: limit pipeline permissions to read-only

---

hw/xnest/Screen.c
meson.build

In xnestOpenScreen(), some compilers/analyzers spitting out a false alarm on
`defaultVisual` field potentially used uninitialized. This can't practically
happen, but not all compilers/analyzers really can see that.
Adding a zero initializer doesn't cost us anything, so silencing that false
alarm is trivial.

Xnest: fix analyzer warning on uninitialized `DefaultVisual`

---

Xext/vidmode.c

The monitor values (vendor and model) accidentally had been copied at the start of the payload, instead of being appended after the previously copied data, thus corrupting the reply and causing some clients to hang.

xf86vidmode: fix result copying in ProcVidModeGetMonitor()

---

hw/xfree86/loader/loadmod.c

In CheckVersion() the errtype variable is used in two separate scopes, but not globally, so it's cleaner to have it only in the scopes that are actually using it.
Reminder: should go into maint-25.0

xfree86: loadmod: locally scope the errtype variable

---

hw/xfree86/compat/README
hw/xfree86/compat/clientexception.c
hw/xfree86/compat/log.c
hw/xfree86/compat/meson.build
hw/xfree86/compat/nvidiabug.c
hw/xfree86/compat/xf86_compat.h

Consolidate the redundant warnings into generic functions.

xfree86: compat: consolidate logging

---

Xext/meson.build
Xext/namespace/meson.build
Xi/meson.build
composite/meson.build
config/meson.build
damageext/meson.build
dbe/meson.build
dix/meson.build
dri3/meson.build
exa/meson.build
fb/meson.build
glx/meson.build
mi/meson.build
miext/damage/meson.build
miext/rootless/meson.build
miext/shadow/meson.build
miext/sync/meson.build
os/meson.build
present/meson.build
pseudoramiX/meson.build
randr/meson.build
record/meson.build
render/meson.build
xfixes/meson.build
xkb/meson.build

this was producing static libraries named "liblibsomething.a"

remove "lib" prefix in static_library in meson.build

---

hw/kdrive/ephyr/ephyrinit.c
hw/kdrive/src/kdrive.c
hw/kdrive/src/kdrive.h
mi/mipointer.c

Same as https://github.com/X11Libre/xserver/pull/317
@metux Should we really special-case another hook, or should we just move all of these calls
after pScreen->CloseScreen in dix/screen_hooks.c ?

mi: move miPointerCloseScreen to hookPostClose

---

hw/vfb/InitOutput.c
hw/xnest/Init.c

Obsolete since 17 years now, probably just forgotten to clean up.
Fixing compiler warning on missing prototype.

drop unused DarwinHandleGUI()

---

Xext/namespace/hook-windowproperty.c

Not used in this file, so no need to keep it around anymore.

namespace: drop unused winIsRoot()

---

.github/scripts/install-prereq.sh
.github/scripts/util.sh

macos build broke due changes in 3rdparty repos (xts, etc). we shouldn't use master branches, but specific commits instead.

[25.0] fix macos build

---

glx/glxcontext.h
glx/glxdrawable.h
glx/glxext.h
glx/glxscreens.h
glx/glxserver.h
glx/glxutil.h
glx/indirect_table.c
glx/singlesize.h
glx/unpack.h
glx/vndserver_priv.h
glx/vndservervendor.h

The consumers always need to include <dix-config.h> at the very top
anyways, so no need to also include it (with extra guards) from
internal headers.

glx: drop including dix-config.h from internal includes

---

randr/rroutput.c

X has various ways to deal with DPI but all of the current methods have some drawback (single global value, manually calculating from physical dimensions, etc.) What is lacking is a simple value per output that users and applications can use to communicate desired scaling values. Fortunately, a generic output property mechanism already exists. And they already send events whenever there is a change. So all we have to do is make an "official" property for people to agree on and enshrine it. In that case, all outputs can just always have the DPI property set to something. In most cases, this will be 96 (the default), but one could use the -dpi argument when launching or and that value will be used instead. The intention is that 96 is the base that is equivalent to 1x scaling. i.e. 192 would …

randr: set initial DPI property to a default value for all outputs

---

dix/meson.build
dix/rpcbuf.c
dix/rpcbuf_priv.h

Since so many request handlers have to assemble complex reply payloads, we've got a lot complexity on counting the needed space and filling in the data into the right places.
Thus adding a little dynamic buffer structure, where one just can append data arbitrarily. The buffer will automatically allocate memory as-needed and finally leave everything in a big memory block for later write-out.

dix: add buffer helper for rpc payload assembly

---

Xext/vidmode.c

A clock entry is 32 bits instead of 8 bits long.

vidmode: fix ProcVidModeGetDotClocks() reply size computation

---

dix/rpcbuf.c
dix/rpcbuf_priv.h

The existing x_rpcbuf_write_string() function is just writing the string w/o trailing zero. It's for cases where the string length is known by other means (eg. some header field). In cases where we also need the trailing zero written (eg. when sending lists of strings) this isn't sufficient.
Thus introducing another variant of this function, which is always writing a leading zero. Using this one, the string's characters will be followed by 1, 2 or 3 zeros (and also be 32bit aligned)

dix: rpcbuf: add x_rpcbuf_write_string_0t_pad()

---

doc/Xserver-spec.xml
include/dix.h

Not used anymore, and not part of ABI, so no need to keep it around any longer.

include: drop obsolete WriteReplyToClient() macro

---

dix/dix_priv.h

Adding convenience function for writing out rpc buffer contents to client and clear the buffer (free it's memory) afterwards.

dix: add WriteRpcbufToClient()

---

dix/rpcbuf_priv.h

add x_rpcbuf_wsize_units() to retrieve the amount of data written into the buffer - in 4-byte units.

dix: rpcbuf: add getter for 4-byte units needed to store buffer contents

---

os/osdep.h

usage:
__size_assert(typename, size);
if the type's size (calculated by sizeof) doesn't match the asserted size, an illegal dummy type will be constructed, thus compilation fails.

os: osdep: add macro for compile-time type size assert

---

hw/xfree86/i2c/xf86i2c.c
hw/xfree86/i2c/xf86i2c.h

name parameter should be const char *

xfree86: fix xf86I2CBusInit() prototype

---

hw/xfree86/fbdevhw/fbdevhw.c
hw/xfree86/fbdevhw/fbdevhw.h

when passing in names that may be const or literals, the corresponding function parameters should be `const char*` instead of `char *`.

fbdevhw: fix const char arguments

---

.github/scripts/install-prereq.sh
.github/scripts/util.sh

After the recent fixes, no patching it required to build on Mac.
Closes: #345

.github: bump xts to current master

---

hw/xfree86/i2c/xf86i2c.h

The bus name is always assigned to string literals, thus pointing to constant data.

xfree86: i2c: constify I2CBusRec::name

---

Xext/namespace/hook-selection.c
Xext/xres.c
Xext/xselinux_hooks.c
Xext/xvmain.c
Xi/extinit.c
Xi/xiproperty.c
dix/dix_priv.h
glamor/glamor_xv.c
hw/vfb/InitInput.c
hw/xfree86/common/xf86Events.c
hw/xfree86/common/xf86Init.c
hw/xfree86/common/xf86Xinput.c
hw/xfree86/ddc/ddcProperty.c
hw/xfree86/drivers/modesetting/drmmode_display.c
hw/xfree86/modes/xf86Crtc.c
hw/xfree86/modes/xf86RandR12.c
hw/xnest/Font.c
hw/xquartz/applewm.c
hw/xquartz/xpr/xprFrame.c
hw/xwin/win.h
miext/rootless/rootlessWindow.c
randr/rrcrtc.c
randr/rrmonitor.c
randr/rroutput.c
randr/rrproperty.c
randr/rrprovider.c
xfixes/cursor.c
xkb/ddxBeep.c
xkb/xkbDflts.h
xkb/xkbInit.c

add helpers dixGetAtomID() and dixAddAtom() and use them instead of directly calling MakeAtom() or extra local macros.

add helpers for atom creation and retrieval

---

.github/scripts/ubuntu/install-pkg.sh

Should hopefully build without it; if not, we should fix that

Remove libselinux1-dev

---

dix/generate-atoms
randr/randrstr.h

This symbol is always defined, and the header is always present, so no need to check for it.

dix: drop using HAVE_DIX_CONFIG_H

---

randr/rrprovider.c

The commit 30cec78 incorrectly changed RRInitPrimeSyncProps to not create the atom if it doesn't exist.
recreated https://github.com/X11Libre/xserver/pull/464, which was closed due source repo deletion.

randr: fix prime sync atom not created correctly

---

mi/midispcur.c
render/picture.c

This fixes two segfaults at exit for intel driver. At screen closing `sna_late_close_screen` needs to destroy the cursor and the glyphs cache using `FreePicture`, which in turn needs privates that has already been released by `miDCCloseScreen` and `PictureScreenClose` executed earlier because they are in pre hooks.
Closes: https://github.com/X11Libre/xf86-video-intel/issues/7

Make miDCCloseScreen and PictureScreenClose post-hooks 

---

meson.build

Related to #397.
FreeBSD uses [libudev-devd](https://github.com/wulf7/libudev-devd) as a wrapper specifically intended for X.Org and libinput.
The udev options should be available for it.
Signed-off-by: b-aaz <b-aazbsd.proton.me>

meson.build: Enabled udev for FreeBSD.

---

include/fd_notify.h
include/meson.build
include/os.h
os/ospoll.c

These defines are already public, used by consumers of SetNotifyFd(), but also needed in places where os.h cannot be included.

os: move X_NOTIFY_* defines to separate header

---

os/osdep.h
os/xdmcp.h

xdmcp.h is using types from <X11/Xdmcp.h>, but forgot to include it. This just popped up with building w/ -Dxdmcp=false, because that file was included in the wrong place (osdep.h) and only conditionally.

os: xdmcp: fix missing include of <X11/Xdmcp.h>

---

config/config.c
meson.build

Implement what was discussed in https://github.com/X11Libre/xserver/issues/478
Use dependency() instead of cc.check_header(), as the former is the intended way to check for dependencies.
cc.check_headers would turn udev on on systems where libudev.h is present, but libudev.pc isn't.
Thos would do the wrong thing on systems where the admin wants to have that header for some reason, but doesn't want programs to use libudev.
We also keep udev and udev_kms a tristate, so we try to do the right thing when the user doesn't explicitly pass values for udev and udev_kms.
@metux @callmetango @b-aaz @dec05eba Thoughts?

meson.build: Check for libudev directly, instead of our flimsy os-speciffic guessing

---

Xext/geext.c
randr/rrsdispatch.c
record/record.c

The length field in requests shouldn't be directly used anymore, because it's not compatible with big requests.
Instead everybody should use client->req_len.
(the only remaining user is within connection setup)

cleanup remaining users of request length field

---

os/log.c

This patch fixes Xserver crashes when evdev or synaptics input drivers are used. These (and maybe other) driver use alternate forms "%#..." in formats for xf86IDrvLogVerb() function, which in turn uses signal-safe vpnprintf(). The last function does not recognize alternate forms and exits abnormally, which causes Xserver to crash. The patch make vpnprintf() to ignore alternate forms.
Closes: https://github.com/X11Libre/xserver/issues/498

xserver: os/log.c: ignore alternate forms in log formats

---

hw/xfree86/common/xf86Config.c
include/meson.build
include/misc.h
include/xorg-server.h.meson.in
os/osdep.h
os/osinit.c

Both are potentially tunable variables, and MAXCLIENTS is (still) used by intel-driver, but also by os specific parts that must not include misc.h

meson: move MAXCLIENTS and LIMITCLIENTS into dix-config.h

---

hw/xwin/win.h

xwin: win.h: missing include of dix/dix_priv.h

---

mi/mieq.c

mingw doens't support `%zu` printf pattern yet.

mi: use %lu instead of %zu in ErrorF() call

---

glamor/glamor_egl.c

GBM_BO_USE_SCANOUT is not always supported.
Handle the case when it is unsupported.
@metux @dec05eba @mikedld Please take a look

glamor: handle if GBM_BO_USE_SCANOUT is not supported

---

Xext/panoramiX.c
dix/dix_priv.h

Theoretically, sizeof() on protocol structs should always give the actual network size. But in order to make sure, that some compiler doens't do anything else - or some header's not entirely correct, adding some static asserts.

static asserts for protocol struct sizes

---

miext/damage/damage.c
miext/damage/damage.h

This is the second half of https://github.com/X11Libre/xserver/pull/329:
allow damage driver hooks to be NULL, if driver wants no neither default nor its own implementation.

damage: allow driver hooks to be NULL

---

Xext/xvdisp.c

Instead of complex macro machinery, just move the conditional swapping directly into request handlers.
Factored out of https://github.com/X11Libre/xserver/pull/386

xv: inline SWrite*Reply() functions

---

os/Xtrans.c

Win32 does not have utsname(), but gethostname(), so we need a separate implementation of _XSERVTransGetHostname() here.

os: xtrans: _XSERVTransGetHostname() variant for mingw target

---

os/Xtrans.c
os/Xtrans.h
os/Xtransint.h
os/Xtranslcl.c
os/Xtranssock.c

It's not used anywhere, so no need to keep it around anymore. We can also dispose the corresponding connection driver's procs here.

os: xtrans: drop _XSERVTransReadv() et al

---

os/Xtrans.c

That's an ancient symbol, which had been replaced by O_NDELAY long ago.

os: xtrans: drop use of FNDELAY

---

Xext/sync.c

We neither need to guard including <sys/time.h> from mingw, nor do we need that include here at all.

Xext: sync: drop unneeded include of <sys/time.h>

---

hw/xfree86/common/xf86Xinput.c
hw/xfree86/common/xf86Xinput_priv.h
hw/xfree86/common/xf86platformBus.c
hw/xfree86/man/xorg.conf.man
hw/xfree86/parser/InputClass.c
hw/xfree86/parser/OutputClass.c
hw/xfree86/parser/configProcs.h
hw/xfree86/parser/meson.build
hw/xfree86/parser/patterns.c
hw/xfree86/parser/xf86Parser.h
hw/xfree86/parser/xf86Parser_priv.h

The code that matches devices against input/output classes is tangled and difficult to track and extend, in particular, because there are different matching modes for different device attributes: case (in)sensitive, pathnames etc.  Sometimes it is convenient to set parameters for a specific device (in old days I used this to create multiseat configurations). In this case more complicated conditions, in particular, REs, come in handy. For example, this is a (slightly modified) excerpt from a real config (**updated with a new version of the PR**):
```
Section "InputClass"
Identifier     "Keyboard-at-seat"
MatchProduct   "~/(Translated|Raw) Set 2 keyboard$"
MatchIsKeyboard "on"
MatchLayout    "!Seat0"
Driver         "evdev"
Option         "Ignore" "on"
Option         "XkbRules" "evdev" …
```

hw/xfree86/parser: Refactor InputClass/OutputClass matching code and allow regular expressions (Enhancement)

---

hw/kdrive/meson.build
hw/meson.build
meson.build

As more kdrive-based servers are coming, it's time to refactor the meson structure a little bit, so all kdrive specific logic is in its own subdir.

kdrive: move ephyr build option check into kdrive's meson.build

---

os/connection.c
os/io.c
os/osdep.h

The FlushClient() logic is pretty complicated and not entirely trivial to understand. Part of that coming from the fact that it's not just flushing (writing out client output buffer), but also can optionally send extra data.
It's much simpler if we split off the separate topics (make buffer room, write out the buffer, write more data) into separate functions.
This PR also removes one of the two users of _XSERVTransWritev(). In combination with https://github.com/X11Libre/xserver/pull/519, this functions becomes obsolete, and so allows for more cleanups in xtrans.

os: io: simplify FlushClient() et al

---

glamor/glamor_utils.h

On FreeBSD the ALIGN macro already exists in the standard headers, so we sholdn't redefine it here.

glamor: don't redefine ALIGN macro if it exists

---

glx/glxscreens.h
include/glx_extinit.h

../glx/indirect_table.c
In file included from ../glx/indirect_table.c:28:
In file included from ../glx/glxserver.h:66:
../include/glx_extinit.h:33:28: warning: redefinition of typedef '__GLXscreen' is a C11 feature [-Wtypedef-redefinition]
33 | typedef struct __GLXscreen __GLXscreen;
|                            ^
../glx/glxscreens.h:113:28: note: previous definition is here
113 | typedef struct __GLXscreen __GLXscreen;
|                            ^

glx: fix duplicate typedef

---

hw/kdrive/ephyr/meson.build

For strange reaons, nanosleep() is in libpthread on mingw platform, so we have to link it here.

kdrive: xephyr: link pthread on mingw for nanosleep()

---

Xext/xf86bigfont.c
Xext/xvdisp.c
exa/exa.c
exa/exa_priv.h
fb/fboverlay.c
hw/vfb/InitOutput.c
hw/xfree86/sdksyms.sh
hw/xnest/Args.c
hw/xquartz/darwin.c
include/meson.build
include/xorg-server.h.meson.in
mi/miinitext.c
mi/miscrinit.c

some bit better naming for config symbols.
Yet leaving the old one defined, until all drivers have kept up.

meson: rename symbol MITSHM to CONFIG_MITSHM

---

os/xprintf.c

It's better coding style to include the header with prototypes for our own functions directly, instead of relying on it being included indirectly.

os: xprintf: fix includes

---

hw/kdrive/ephyr/hostx.c

Win32 doesn't have SysV IPC, so we need to build it w/o this here.

kdrive: allow win32 build w/o sysv ipc

---

Xext/namespace/hook-init-rootwindow.c
Xext/namespace/hook-resource.c
Xext/namespace/hook-windowproperty.c

For printing 32bit integers, we need to use PR*32 macros.

Xnamespace: fix printf patterns

---

hw/xfree86/os-support/shared/drm_platform.c

../hw/xfree86/os-support/shared/drm_platform.c:37:13: warning: variable 'paused' is uninitialized when used here [-Wuninitialized]
37 |         if (paused) {
|             ^~~~~~
../hw/xfree86/os-support/shared/drm_platform.c:31:16: note: initialize the variable 'paused' to silence this warning
31 |     Bool paused, server_fd = FALSE;
|                ^
|                 = 0
1 warning generated.

xfree86: drm_platform: fix warning on potentially unitialized variable

---

hw/xfree86/fbdevhw/fbdevhw.c
hw/xfree86/fbdevhw/fbdevhw.h

the device name parameter should be const char *.

xfree86: fbdevhw: fix fbdevHWProbe() parameter

---

os/ospoll.c

os: ospoll: add missing include of <string.h>

---

os/ospoll.c
os/ospoll.h

Low level OS specific code should not depend on higher level protocol headers. This also removes yet another conflict with win32/mingw headers.

os: ospoll: use stdbool instead of X11's Bool

---

os/ospoll.c

We're using assert() here, so need to include <assert.h>

os: ospoll: add missing include of <assert.h>

---

include/fd_notify.h
include/meson.build
include/os.h
os/ospoll.c

On WIN32 we need to include winsock2.h, but we can't include misc.h here becaues it pulling in X11 headers that are conflicting with win32 headers.

[25.0] os: ospoll: include winsock2.h on WIN32 instead of misc.h

---

render/picture.h

Both types are already binary equal: both are enums using the same bit values, but from compiler's perspective they're still different types, so it's warning.
>   ../glamor/glamor_trapezoid.c:123:47: warning: implicit conversion from
>   enumeration type 'PictFormatShort' (aka 'enum _PictFormatShort') to different
>   enumeration type 'pixman_format_code_t' [-Wenum-conversion]
>     123 |     image = pixman_image_create_bits(picture->format,
>          |             ~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~^~~~~~
>    1 warning generated.
The PICT_* fields, values and macros are relics from pre-pixman days (pixman, historically, essentially is the PICT_* stuff moved out to separate library) This has been a practical way for doing the transition from the old internal PICT_* code to pixman. Now …

render: picture: make PictFormatShort equal to pixman_format_code_t

---

hw/kdrive/src/kdrive.h
hw/kdrive/src/kinput.c

This will be needed by Xfbdev's keyboard driver, which cannot work with input threads yet.
Yet another preparation for
https://github.com/X11Libre/xserver/pull/351

kdrive: add fd notification machinery

---

composite/compinit.c
exa/exa_glyphs.c
exa/exa_render.c
fb/fbtrap.c
glamor/glamor_picture.c
glamor/glamor_program.c
glamor/glamor_program.h
glamor/glamor_render.c
glamor/glamor_transfer.c
glamor/glamor_utils.h
render/glyph.c
render/mipict.c
render/picture.c
render/render.c

PICT_FORMAT_* are just aliases to PIXMAN_FORMAT_* back from when PICT_* had been moved out into pixman.

use PIXMAN_FORMAT_* defines instead of PICT_FORMAT_* ones

---

hw/xfree86/drivers/video/modesetting/meson.build

Fix the path for the symbol test to make sure it can find the library.

xfree86: modesetting: meson: fix symbol test path

---

hw/vfb/InitOutput.c
hw/xfree86/parser/scan.c
os/Xtrans.c
os/Xtrans.h
os/Xtransutil.c
os/access.c
os/meson.build
os/osdep.h
os/utils.c
os/xhostname.c
os/xhostname.h

* os layer: add a function for safe hostname retrieval using a fixed-size buffer struct 
* this buffer is carefully cleared and the name string always zero-terminated
* simplify callers of gethostname() by using this function

os: encapsulate OS specific aspects of hostname retrieval into xhostname() function 

---

os/osdep.h

This function is called by nvidia390 legacy proprietary driver. With it the driver mostly works, cf https://github.com/ONykyf/nvidia390-slackbuild , provided https://github.com/X11Libre/xserver/pull/525 is also applied.

xserver: {include, os}: reexport TimerForce()

---

randr/rrcrtc.c

Simplify reply payload assembly and byte-swap by using x_rpcbuf_t.

randr: ProcRRGetCrtcGamma(): use x_rpcbuf_t for reply payload assembly

---

hw/xfree86/loader/loadmod.c
hw/xfree86/meson.build

* switch major version from 25.0 to 25
* make loader respect legacy 25.0 module dirs (to be removed in version
26)
Fixes: #646
Signed-off-by: callmetango <callmetango@users.noreply.github.com>

xfree86: enable semantic versioning

---

Xext/namespace/config.c

The namespace config still has the "container" directive, which should have been named "namespace". It's a leftover from the original working draft that was named "container extension".
For the time being, keep backwards compatibility by allowing both tokens "container" as well as "namespace" for the same directive. But consider the old token as deprecated, it shouldn't be used anymore and might go away in the near future.
See also:
https://github.com/X11Libre/xserver/pull/665
https://github.com/X11Libre/xserver/pull/551

namespace: allow "namespace" config directive instead of "container"

---

Xext/panoramiX.c

take way the extra scope / indention on the `if (nbox)` statement and use `continue` instead.
Hint: for easier review, one can use `git diff -w` in order to suppress the indention-only changes.

panoramiX: XineramaGetImageData(): simplify the loop

---

Xext/vidmode.c

bytes_to_int32 already adds padding, no need to compute that too.
@metux @callmetango Thoughts?

dix: Xext: replace bytes_to_int32(pad_to_int32(x)) with bytes_to_int32(x)

---

Xext/xvdisp.c
xkb/xkb.c

In the request handlers, use x_rpcbuf_wsize_units() for payload length computation.

treewide: use  use x_rpcbuf_wsize_units() instead of rpcbuf.wpos

---

xfixes/cursor.c

Use x_rpcbuf_t for reply payload assembly, and X_SEND_REPLY_WITH_RPCBUF() for sending out the whole replies.

xfixes: cursor: use x_rpcbuf_t and X_SEND_REPLY_WITH_RPCBUF()

---

dix/rpcbuf_priv.h

Add a helper for writing pascal-type strings: the counter is written as CARD16, then followed by the string characters (w/o zero), and finally everything padded up to full protocol units.
This encoding is used in various places throughout the Xserver, eg. in xkb.

dix: rpcbuf: add x_rpcbuf_write_counted_string_pad()

---

xkb/xkb.c

Since no consumer of this rpcbuf is writing directly to the underlying buffer space anymore, there's no need to explicitly make room.

xkb: ProcXkbGetKbdByName(): drop obsolete x_rpcbuf_makeroom() call

---

xkb/xkb.c

Use x_rpbuf_t instead of raw buffer for assembling and byte-swapping indicator map payload.

xkb: XkbAssembleIndicatorMap(): use x_rpcbuf_t

---

xkb/xkb.c

Use rpcbuf for assembling and byte-swapping xkb names payload.

xkb: XkbAssembleNames(): use x_rpcbuf_t for payload assembly

---

Xext/panoramiX.c

Split out the code inside the big for-each-screen loop into separate function.

panoramix: XineramaGetImageData() split out code inside the big loop

---

Xext/sync.c
Xext/vidmode.c
Xext/xf86bigfont.c
dix/dixfonts.c
dix/window.c
hw/xfree86/dri/xf86dri.c
xkb/xkb.c

Add and use macro X_REPLY_HEADER_UNITS() for computing how many
extra protocol units are needed for a reply header (for .length field)

treewide: macro for computing extra units needed for reply header

---

Xext/shape.c

xext: shape: use X_SEND_REPLY_SIMPLE()

---

Xext/xf86bigfont.c

xext: xf86bigfont: use X_SEND_REPLY_SIMPLE()

---

Xext/xtest.c

xext: xtest: use X_SEND_REPLY_SIMPLE()

---

Xext/dpms.c

xext: dpms: use X_SEND_REPLY_SIMPLE()

---

Xext/xf86bigfont.c

Use x_rpcbuf_t instead of our own local buffer for the reply payload assembly and byte-swapping.

xf86bigfont: ProcXF86BigfontQueryFont(): use x_rpcbuf_t

---

Xext/xcmisc.c

xext: xcmisc: use X_SEND_REPLY_SIMPLE()

---

xkb/xkb.c

Use x_rpcbuf_t for payload chunk assembly / byte-swapping.

xkb: XkbWriteGeomSections(): use x_rpcbuf_t

---

Xext/xres.c

Use the new X_SEND_REPLY_WITH_RPCBUF() macro for final reply write out.

xres: ProcXResQueryClients(): use X_SEND_REPLY_WITH_RPCBUF() macro

---

dbe/dbe.c

dbe: xtest: use X_SEND_REPLY_SIMPLE()

---

Xext/security.c

xext: security: use X_SEND_REPLY_SIMPLE()

---

Xext/panoramiX.c
Xext/panoramiXprocs.c

xext: panoramix: use X_SEND_REPLY_SIMPLE()

---

Xext/sync.c

xext: sync: use X_SEND_REPLY_SIMPLE()

---

dix/devices.c
dix/dispatch.c
dix/property.c

Use the new X_SEND_REPLY_WITH_RPCBUF() macro for final reply write out.

dix: replace WriteRpcbufToClient() by X_SEND_REPLY_WITH_RPCBUF() macro

---

Xext/panoramiX.c
Xext/panoramiXprocs.c
Xext/vidmode.c
Xext/xcmisc.c
Xext/xf86bigfont.c
Xext/xvdisp.c

Use the new X_SEND_REPLY_WITH_RPCBUF() macro for final reply write out.

Xext: replace WriteRpcbufToClient() by X_SEND_REPLY_WITH_RPCBUF() macro

---

dix/dispatch.c
dix/events.c
dix/extension.c
dix/property.c
dix/selection.c
dix/window.c

dix: use X_SEND_REPLY_SIMPLE()

---

Xext/bigreq.c

xext: bigreq: use X_SEND_REPLY_SIMPLE()

---

Xext/sync.c

Use x_rpcbuf_t for reply payload assembly, and sending out the whole
thing via X_SEND_REPLY_WITH_RPCBUF().

sync: ProcSyncListSystemCounters(): use x_rpcbuf_t

---

glx/glxcmds.c
glx/vndcmds.c

glx: xtest: use X_SEND_REPLY_SIMPLE()

---

hw/xfree86/loader/loadmod.c

All other recent commits were already made in Xlibre.
Only this remains, which I'm not sure about: https://gitlab.freedesktop.org/xorg/xserver/-/commit/4ca8b9a47459d0e0827556da48cc5f1bfe873952
Do we build xf86bigfont in CI?

Backport from Xorg

---

hw/xfree86/drivers/video/modesetting/drmmode_display.c

Split out from https://github.com/X11Libre/xserver/pull/559

modesetting: Check for NULL mode_output before printing warning message

---

xkb/xkb.c

Add extra check for comparing the actually written sub-payload sizes
with their previously computed ones. This is meant for troubeshooting
while still stabelizing the previous, not entirely trivial commits.

xkb: ProcXkbGetKbdByName(): extra payload size sanity check

---

.github/scripts/git-smart-checkout.sh
.github/scripts/install-prereq.sh
.github/scripts/util.sh

Several sites we need to clone our dependencies from (eg. freedesktop.org)
have pretty unreliable servers, so our CI jobs often fail just because
of temporary clone failure.
Therefore adding a separate cloning script, which is more clever with automatic
retries, but it also tries to keep the traffic low (eg. trying shallow clones
if possible) and automatically detecting whether we're pulling a ref or a
direct commit.

.github: use a smarter cloning script

---

Xext/vidmode.c

Fixes a bug I touched on about at https://github.com/X11Libre/xserver/pull/804#issuecomment-3224071823
struct xXF86VidModeModeInfo is defined as such, with comments added by me:
```
typedef struct {
CARD32      dotclock;
CARD16      hdisplay;
CARD16      hsyncstart;
CARD16      hsyncend;
CARD16      htotal;
CARD32      hskew;
CARD16      vdisplay; /* 1 */
CARD16      vsyncstart; /* 2 */
CARD16      vsyncend; /* 3 */
CARD16      vtotal; /* 4 */
CARD16      pad1; /* 5 */
/*  CARD16      implicit, but in memory; */ /* 6 */
CARD32      flags;
CARD32      reserved1;
CARD32      reserved2;
CARD32      reserved3;
CARD32      privsize;
} xXF86VidModeModeInfo;
```
No idea why this extra padding was added, which breaks alignment, but it is there, and we have to take it into account.
@metux These …

Xext: add missing implicit padding to vidmode fillModeInfoV2

---

hw/xfree86/drivers/video/modesetting/driver.c
hw/xfree86/drivers/video/modesetting/driver.h
hw/xfree86/drivers/video/modesetting/drmmode_display.c
hw/xfree86/drivers/video/modesetting/drmmode_display.h
include/meson.build

Since 1f41320e1c4274c4d47f5f381d202aef3b7415c7, the modesetting driver has been brute forcing the kernel trying to find supported cursor dimensions, this in theory was a decent solution however it turns out that many drivers really don't like this happening, resulting in cursors being corrupted or incorrectly sized since the stride was being changed between probes.
In 2024, the kernel adopted the `SIZE_HINTS` property which ended up being solely supported by the `i915` driver since Linux 6.10, providing hints for the supported dimensions for a cursor plane, which makes the mentioned commit no longer needed.
So revert the commit mostly and instead probe the DRM planes for that value, if it isn't available then use whatever the kernel gives us through `DRM_CAP_CURSOR_[WIDTH|HEIGHT]`, it …

modesetting: Overhaul and fix cursor probing.

---

xkb/xkb.c

Use the X_SEND_REPLY_SIMPLE() macro for sending simple replies.

xkb: send simple replies via X_SEND_REPLY_SIMPLE()

---

include/os.h

Fix pedantic warnings:
> ../include/os.h:144:71: warning: ISO C does not allow extra ‘;’ outside of a function [-Wpedantic]
>   144 | XNFalloc(unsigned long /*amount */ ) __attribute__((returns_nonnull));;
> ../include/os.h:158:76: warning: ISO C does not allow extra ‘;’ outside of a function [-Wpedantic]
>   158 | XNFcallocarray(size_t nmemb, size_t size) __attribute__((returns_nonnull));;

include: os.h: fix extra ;

---

dix/dixfonts.c
hw/xfree86/dri/dri.c
mi/mieq.c

Do it the ISO C way, so -pendantic is shouting a little bit less.

treewide: explicitly cast %p printf parameters to void*

---

Xi/xiselectev.c

For better readability, declare the variables only where they're used,
and try to scope them, instead of declaring them all on the very top.

Xi: ProcXISelectEvents() declare variables where needed

---

dix/swaprep.c
include/swaprep.h

Not used anywhere, neither exported.

dix: drop obsolete Swap32Write()

---

Xi/xiselectev.c

Xi: ProcXIQueryPointer(): use x_rpcbuf_t

---

Xext/vidmode.c

Since https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/101 got merged, the padding for xXF86VidModeModeInfo is now explicit.
The change is only cosmetic, so users of older protocol headers will not be affected.

Xext: fix comments when assembling xXF86VidModeModeInfo reply

---

fb/fbpixmap.c
hw/xnest/Pixmap.c
hw/xwin/winmultiwindowwindow.c

The PixmapRec is already calloc()'ed, so no need for additional zero-writes
into individual fields. This also removes some unncessary #ifdefs.

treewide: drop unnecessary pixmap field initialization

---

dix/dixfonts.c

Use X_SEND_REPLY_SIMPLE() for writing out the trivial empty reply.

dix: dixfonts: doListFontsWithInfo(): use X_SEND_REPLY_SIMPLE()

---

Xext/panoramiX.c
Xext/panoramiXprocs.c
Xext/shape.c
Xext/vidmode.c
Xext/xcmisc.c
Xext/xf86bigfont.c
Xext/xres.c
Xext/xvdisp.c
Xi/getkmap.c
Xi/getprop.c
Xi/getselev.c
Xi/xiproperty.c
dbe/dbe.c
dix/devices.c
dix/dispatch.c
dix/property.c
randr/rrcrtc.c
randr/rrmonitor.c
randr/rroutput.c
randr/rrproperty.c
randr/rrproviderproperty.c
xfixes/cursor.c
xfixes/region.c
xkb/xkb.c

The macro will automatically return BadAlloc if the buffer is broken,
otherwise Success. Thus, we don't need extra prior rpcbuf check.

treewide return code of X_SEND_REPLY_WITH_RPCBUF()

---

composite/compext.c

When iterating screen lists, consistently use the same variable name
`walkScreenIdx` for holding current screen index everywhere.

composite: canonical `walkScreenIdx` variable on screen list iterations

---

dix/dixfonts.c

As preparation for moving doListFontsWithInfo() (and it's callers) to
x_rpcbuf_t, inline the SwapFonts() call into the caller function.
SwapFonts() has several problems, eg. directly operating on a buffer that's
holding xQueryFontReply struct (which isn't the correct one, just happens to
match) as well as the whole payload.
We first need to get them out of the way, before we can split off the reply
into the (statically declared) header struct and the (x_rpcbuf_t-filled)
payload.

dix: doListFontsWithInfo(): inline SwapFonts() call

---

dix/swaprep.c
include/swaprep.h

Not used anywhere, neither exported, so no need to keep it
around any longer.

dix: drop unused CopySwap32Write()

---

render/animcur.c
render/filter.c
render/glyph.c
render/picture.c
render/render.c

When iterating screen lists, consistently use the same variable name
`walkScreenIdx` for holding current screen index everywhere.

render: canonical `walkScreenIdx` variable on screen list iterations

---

render/render.c

Use x_rpcbuf_t for reply payload assembly and X_SEND_REPLY_WITH_RPCBUF()

render: ProcRenderQueryPictFormats(): use x_rpcbuf_t

---

Xext/saver.c

The only actually effective line can be easily moved into
ProcScreenSaverQueryInfo()

Xext: saver: inline SProcScreenSaverQueryInfo()

---

xfixes/cursor.c
xfixes/region.c

When iterating screen lists, consistently use the same variable name
`walkScreenIdx` for holding current screen index everywhere.

xfixes: canonical `walkScreenIdx` variable on screen list iterations

---

dix/dispatch.c

dix: ProcQueryColors(): use x_rpcbuf_t

---

hw/kdrive/src/kinput.c

These are just used locally and always assigned at loop body start,
so it's cleaner to declare them locally inside the loop body.

kdrive: KdCursorOffScreen(): move dx and dy into local scope

---

Xi/exevents.c

Only used once as paramter, so we can use its assigned value directly.

Xi: SendEventToAllWindows(): drop unneeded local variable

---

dbe/dbe.c

The code is easier to understand when we don't reuse existing variables
for entirely different things.

dbe: DbeExtensionInit() don't reuse walk variable differently

---

hw/xfree86/dri/xf86dri.c

Cache the screen pointer in local variable, instead of fetching it
from global array several times. Follow-up commits will use some
inline helper for that.

xfree86: dri: ProcXF86DRIGetDrawableInfo(): cache screen pointer

---

Xext/xvmc.c

In 22 years, nobody ever implemented byte-swapping here.
Fixes: 9508a382f8a9f241dab097d921b6d290c1c3a776

Xvmc: add reply byte-swapping

---

glx/glxcmds.c
glx/glxcmdsswap.c
glx/single2swap.c
glx/unpack.h

We have an optimized function for this, so use it.

glx: replace __GLX_SWAP_INT_ARRAY() by SwapLongs()

---

test/misc.c

* a bit more type-safe and cleaner to read
* cache the screen pointer on cache
* preparation for upcoming refactoring of screen array access

test: misc: turn set_screen() macro into an inline function

---

glx/vnd_dispatch_stubs.c

Move the steps for retrieving the vendor object for given screen
into a little helper function.

glx: consolidate retrieval of vendor for screen

---

mi/midispcur.c

skip cycle via `continue` instead of having a big if{} block.

mi: miDCDeviceCleanup(): little loop simplification

---

dix/dispatch.c

dix: ProcAllocColorPlanes(): use x_rpcbuf_t

---

dix/dispatch.c
dix/dix_priv.h
dix/dixfonts.c
include/dixfont.h

dix: ProcGetFontPath(): use x_rpcbuf_t

---

dix/cursor.c
dix/dispatch.c
dix/dixfonts.c
dix/dixutils.c
dix/enterleave.c
dix/events.c
dix/inpututils.c
dix/main.c
dix/privates.c
dix/property.c
dix/window.c

When iterating screen lists, consistently use the same variable name
`walkScreenIdx` for holding current screen index everywhere.

dix: canonical `walkScreenIdx` variable on screen list iterations

---

hw/kdrive/src/kinput.c

in preparation of upcoming generic screen iterator macros, already
rename the index variable to what the macro will be using.

kdrive: KdCursorOffScreen(): canonical screen iterator index

---

dbe/dbe.c

dbe: use canonical screen iterator index variable

---

Xext/sync.c
Xext/xvmc.c

Xext: xvmc: use x_rpcbuf_t

---

CONTRIBUTING.md

change 'an' to 'and' in '[...] a short *an* precise subject [...]' and add 'a' in a later line

fix minor spelling mistake in contributing guidelines

---

Xext/shm.c

SHM can *only* be used locally by definition, so the case of having
a byte-swapped client doesn't exist at all.

Xext: shm: drop useless byte-swapping

---

Xext/sync.c

It's so trivial that those few lines can easily be inlined into
the actual request handler.

Xext: sync: inline request swapping

---

dix/window.c

dix: PrintWindowTree(): move locally-used variabes into local scope

---

hw/xfree86/common/xf86AutoConfig.c

scfb driver is the native frame-buffer driver used on both FreeBSD and DragonFlyBSD,
It was not enabled as a fallback on DragonFlyBSD, so enabled it.
The driver:
https://github.com/rayddteam/xf86-video-scfb
Signed-off-by: b-aaz <b-aazbsd@proton.me>

xf86AutoConfig: Enabled autoselction of the scfb driver for DragonFlyBSD.

---

Xext/panoramiX.c
Xext/panoramiX.h
Xext/panoramiXprocs.c
Xext/panoramiXsrv.h
Xext/saver.c
Xext/shape.c
Xext/shm.c
Xext/xvdisp.c
composite/compext.c
damageext/damageext.c
dix/events.c
dix/property.c
dix/window.c
render/render.c
xfixes/region.c

Move the walking loops on Xinerama screens into lambda-esque macros:
the callers look quite like we've been using lambda functions and
closures, but actually are just fancy macro trickery.

Xinerama: lambda-esque macro for walking Xinerama screens

---

glx/glxcmds.c

The name string is supposed to be transmitted as-is, not swapped in
4-byte chunks.

[need-backport] glx: fix wrong swapped encoding in __glXDisp_QueryExtensionsString()

---

hw/kdrive/ephyr/ephyrinit.c
hw/kdrive/fbdev/fbinit.c
hw/kdrive/src/kdrive.c
hw/kdrive/src/kdrive.h

We only have one global screenInfo struct ever, and many other parts of the
Xserver can only operate on global screenInfo, so it's time to phase out
this extra pointer. Once the same has done on the other DDXes, it will
be dropped from InitOutput()'s parameter list.

kdrive: use screenInfo insead of pointer passed to InitOutput()

---

Xext/xf86bigfont.c

In ProcXF86BigfontQueryVersion(), return the retval of the
X_SEND_REPLY_SIMPLE() call.

Xext: xf86bigfont: use retval of X_SEND_REPLY_SIMPLE()

---

Xext/geext.c

Don't need actually need that extra macro, we can just write
&GEClientPrivateKeyRec in those few places.

Xext: geext: drop GEClientPrivateKey

---

damageext/damageext.c
damageext/damageextint.h

* move the stuff only used in .c file there
* drop unnecessary include files

damage: consolidate damageextint.h

---

Xext/xf86bigfont.c

It's doing nothing but calling ProcXF86BigfontQueryVersion(), so
we can call that function directly in the swapped dispatcher and
get rid of SProcXF86BigfontQueryVersion() entirely.

xf86bigfont: drop obsolete SProcXF86BigfontQueryVersion()

---

hw/xfree86/os-support/meson.build

In DragonFlyBSD the host_machine.system() variable is set to 'dragonfly' and does not end with 'bsd'. Changed a check to correctly detect 'dragonfly' as a member of BSD OSs.
bsd/bsd_kmod.c is used for dealing with kernel modules on FreeBSD, enabled this file for DragonFlyBSD too, because they both have the same APIs in this context.

xfree86: os-support: Deal with DFBSD correctly.

---

Xext/xvdisp.c

Fixes: https://github.com/X11Libre/xserver/issues/706

Xext: Fix type mismatch in xvdisp.c

---

hw/xfree86/fbdevhw/fbdevhw.c
hw/xfree86/fbdevhw/man/fbdevhw.man

Now that we know the root couse of what this code tried to fix,
we can safely remove it.
Fixes: https://gitlab.freedesktop.org/xorg/driver/xf86-video-fbdev/-/issues/9
Fixes: https://gitlab.freedesktop.org/xorg/xserver/-/commit/fc78bcca21e767697de6ad4d8e03b6728856f613
Fixes: https://gitlab.freedesktop.org/xorg/xserver/-/commit/a8e41a81909ef74faa38ef12ca35c5d83f7c56a5
Fixes: https://gitlab.freedesktop.org/xorg/xserver/-/commit/728b54528d37ffa27b07c9b181c5ed8d2d359379
Fixes: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1798
Fixes: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1826
Also documents the FRAMEBUFFER envvar.
This pr depends on https://github.com/X11Libre/xserver/pull/998

Fbdevhw followup

---

dix/dix_priv.h

We're trying to use size_t for sizes whereever possible, but WriteToClient()
is part of ABI, so we can't fix it's parameter types - need to explicitly
cast, in order to silence the compiler warnings.

dix: dix_priv.h: cast size value on WriteToClient() calls

---

dix/gc.c

GC's serialNumber field is unsigned int, but DrawableRec's is unsigned long,
so we need to typecast.
It would be better if they all had the same type, but we can't change them easily,
as that might cause ABI break.

dix: ValidateGC(): fix serialNumber assignment

---

dix/dixutils.c
dix/window.c
include/dixstruct.h

this field is used a counter, thus should be unsigned, instead of having
dozens of signess warnings or adding casts to suppress them.

dix: fix ClientRec->numSaved to unsigned

---

xkb/xkb.c

The macro will automatically return BadAlloc if the buffer is broken,
otherwise Success. Thus, we don't need extra prior rpcbuf check.

xkb: ProcXkbGetKbdByName(): use return code of X_SEND_REPLY_WITH_RPCBUF()

---

render/render.c

render: consolidate byte-swapping in ProcRenderQueryPictIndexValues()

---

render/render.c

render: consolidate byte-swapping in ProcRenderCreateGlyphSet()

---

render/render.c

render: consolidate byte-swapping in ProcRenderQueryFilters()

---

meson.build

DragonFlyBSD also uses epoll-shim and it is necessary for DRI3.

meson.build: Enable epoll-shim for DFBSD.

---

.github/scripts/install-prereq.sh

f.d.o is failing too often in recent times, so switching to our own mirrors at github.

.github: use our own mirrors of build dependencies

---

dix/dixutils.c

It's a counter and size value - we're getting lots of signedness warnings,
so use size_t instead of (signed) int.

dix: dixutils: fix signedness of numCallbackListsToCleanup

---

dix/dixutils.c

These are used as counters / sizes, and we're getting lots of warnings
on signedness mismatches. So use size_t instead of (signed) int here.

dix: dixutils: fix signedness of numHandlers and sizeHandlers

---

hw/xfree86/drivers/video/modesetting/drmmode_display.c
hw/xfree86/drivers/video/modesetting/drmmode_display.h

We often use very large cursor sizes, compared to the sizes of the curor glyphs, e.g. 64x64 cursors and 16x16 or smaller glyphs.
This patch makes is so that we only paint the size of the new cursor glyph and clear the old one if needed, instead of painting the entire cursor buffer, which is often far larger than the glyphs.

modesetting: Only paint as much of the cursor image as needed

---

hw/xfree86/common/xf86AutoConfig.c
hw/xfree86/common/xf86Events.c
hw/xfree86/common/xf86platformBus.h
hw/xfree86/common/xf86platformBus_priv.h
hw/xfree86/os-support/linux/systemd-logind.c
hw/xfree86/os-support/shared/platform_noop.c

These xf86_num_platform_devices and xf86_platform_devices fields aren't
_X_EXPORTED, so no drivers can use them - and none are trying so.
Thus move them to internal / non-sdk header.
Not an ABI change.

xfree86: platform bus: move raw device list to internal header

---

hw/xfree86/fbdevhw/fbdevhw.c

The pci probe was broken already, lots of pci devices were not detected as such.
Since fixing it properly required a bit of extra code complexity, and those devices would be detected on the fallback probe, I didn't bother fixing it untill now.
However, there is another problem created by this.
The pci probe was accepting the device passed by the user without doing any checks on it.
This means that in multi-card setups, fbdevhw might claim the wrong pci slot.
Fixing this requires fixing the pci probe in order to try and determine whether the device passed by the user is the same as the pci device passed to the pci probe.
This commit fixes the pci probe.
If no device is passed by the user, the probe finds a pci framebuffer device.
If a device is passed, the pci probe only returns TRUE if …

Fbdevhw pci rework

---

glx/vndcmds.c

This function is used to switch OpenGL contexts. Currently it makes an additional call to clear the current context, which is redundant because the vendor already does this as long both contexts are for the vendor. This patch adds a check to see if vendor is changing before clearing the current context, avoiding some unnecessary calls.

glx: vndcmds: avoid unbinding context within same vendor

---

dri3/dri3_request.c

dri3: Xi: use return value of X_SEND_REPLY_SIMPLE()

---

composite/compext.c

compext: Xi: use return value of X_SEND_REPLY_SIMPLE()

---

randr/rrproperty.c

randr: Xi: use return value of X_SEND_REPLY_SIMPLE()

---

render/render.c

render: consolidate byte-swapping in ProcRenderReferenceGlyphSet()

---

render/render.c

render: consolidate byte-swapping in ProcRenderCreatePicture()

---

Xext/xselinux_ext.c

xselinux: use return code of X_SEND_REPLY_SIMPLE()

---

render/render.c

render: consolidate byte-swapping in ProcRenderFreeGlyphSet()

---

os/Xtrans.c

These aren't used anymore, so no need to keep them any longer.

os: xtrans: drop unused transport table indices

---

Xext/xace.h
include/callback.h
include/dixstruct.h
include/misc.h
include/os.h

This type is already defined in `include/callback.h` - anybody who wants it
most likely needs that include file, too.

include: misc.h: drop duplicate definition of CallbackListPtr

---

hw/kdrive/src/kxv.c

kdrive: fix missing includes of extinit.h

---

composite/compinit.c
composite/compoverlay.c
composite/compwindow.c

composite: fix missing includes of extinit.h

---

randr/rrxinerama.c

randr: fix missing includes of extinit.h

---

render/picture.c

render: fix missing includes of extinit.h

---

hw/xwin/winscrinit.c

xwin: fix missing includes of extinit.h

---

hw/xfree86/common/xf86xv.c
hw/xfree86/common/xf86xvmc.c
hw/xfree86/common/xf86xvpriv.h

Not used by any drivers anymore, so no need to keep it around any longer.

xfree86: drop XF86XvScreenKey field

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbSetGeometry()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbListComponents()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbGetDeviceInfo()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbGetNamedIndicator()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbGetIndicatorState()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbGetMap()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbGetControls()

---

dix/dixutils.c
include/dix.h
include/dixstruct.h

It's only used inside dixutil.c, nowhere else, especially not drivers,
so no need to keep it in public SDK. Safe for ABI-25.

dix: move struct _WorkQueue definition into dixutil.c

---

dbe/dbe.c
dbe/dbestruct.h
dbe/midbe.h

No need for the extra macros, we can just use the corresponding
structs directly.

dbe: replace dbeScreenPrivKey and dbeWindowPrivKey macros

---

Xi/chgprop.c
Xi/extinit.c
Xi/handlers.h

No need to have a hole bunch of extra functions, if we can just easily
inline the few relevant lines.

Xi: inline SProcXChangeDeviceDontPropagateList()

---

render/render.c

render: consolidate byte-swapping in ProcRenderAddGlyphs()

---

hw/xfree86/dri/xf86dri.c
hw/xfree86/dri2/dri2ext.c

The request handler already refusing non-local access, so no need
for any extra swapped handler.

xfree86: dri: drop unnecessary swapped request handler

---

composite/compalloc.c

composite: Only copy bits from the parent pixmap when absolutely necessary
Since https://gitlab.freedesktop.org/xorg/xserver/-/commit/1e728c3e88f6a74b93dc11827c9fcfe7b39ca5a5 ,
Whenever we allocate a composite pixmap, we perform an expensive CopyArea call from the parent pixmap.
This leads to very bad performance when not using a framebuffer driver without shadowfb.
My guess is that this call ends up reading memory from the framebuffer memory directly, which is very slow.
Fixes: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1814
Signed-off-by: stefan11111 <stefan11111@shitposting.expert>

Fix compalloc

---

dix/resource_priv.h
include/resource.h

Only used by Xselinux extension, not by any drivers, so no need to
keep it exported.
Since it's never been used by drivers at all, it's effectively no ABI change,
so can safely be done within ABI-25.

dix: unexport ResourceStateCallback (not used by drivers)

---

Xi/exevents.c
hw/xfree86/common/xf86AutoConfig.c
hw/xfree86/common/xf86Bus.c
hw/xfree86/common/xf86Helper.c
hw/xfree86/common/xf86pciBus.c
hw/xfree86/common/xf86platformBus.c
hw/xfree86/i2c/xf86i2c.c
include/os.h
os/alloc.c
os/osdep.h

Not used by any drivers, no no need to keep it in public SDK.
Since it's not used by drivers, it's effectively not an ABI change,
so can be done within ABI-25.

os: unexport XNFreallocarray()

---

Xext/dpms.c
Xext/saver.c
dix/dispatch.c
dix/main.c
dix/screensaver_priv.h
hw/xfree86/common/xf86Config.c
hw/xwin/winblock.c
include/globals.h
os/WaitFor.c
os/utils.c

Not used by any external drivers, so no need to keep them in public
SDK headers. Since they're never used by drivers, it's effectively
not an ABI change, so can safely be done within ABI-25.

dix: unexport screen saver parameters

---

include/os.h
os/client_priv.h
os/io.c

It's only used by record extension, not used by any drivers at all
(neither FOSS nor proprietary), so it shouldn't be in the public SDK.
Since it's never been used by any driver, it's effectively no ABI change,
so we can safely do this within ABI-25.

os: unexport ReplyCallback

---

hw/xquartz/darwin.c

* the pScreenInfo isn't needed: we're always getting global screenInfo
passed in here (there's only one, globally, anyways)
* use the common iterator variable names
* handle first and auxillary screens all in the same loop
(we can just branch by idx)

xquartz: prepare DarwinAdjustScreenOrigins() for new screen iterators

---

Xi/extinit.c
Xi/handlers.h
Xi/xiquerydevice.c
test/xi2/protocol-xiquerydevice.c

Xi: inline SProcXIQueryDevice()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbSetControls()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbGetState()

---

xkb/xkb.c
xkb/xkbSwap.c

xkb: inline SProcXkbPerClientFlags()

---

render/render.c

render: consolidate byte-swapping in ProcRenderFreePicture()

---

Xext/namespace/hook-client.c
Xext/namespace/namespace.c
Xext/security.c
Xext/xace.c
Xext/xace.h
Xext/xacestr.h
Xext/xres.c
Xext/xselinux_hooks.c
dix/client_priv.h
dix/dispatch.c
dix/dixutils.c

Move the callbacks directly into DIX, since it's actually core infrastructure.
Also simplifying the whole machinery, by just using a simpel CallbackListPtr.

dix: replace XACE_CLIENT_ACCESS by direct callback

---

Xi/extinit.c
Xi/getselev.c
Xi/handlers.h

No need to have a hole bunch of extra functions, if we can just easily
inline the few relevant lines.

Xi: inline SProcXGetSelectedExtensionEvents()

---

Xi/extinit.c
Xi/getprop.c
Xi/handlers.h

No need to have a hole bunch of extra functions, if we can just easily
inline the few relevant lines.

Xi: inline SProcXGetDeviceDontPropagateList()

---

dix/dispatch.c
dix/swapreq.c
dix/tables.c
include/swapreq.h

Yet another step for getting rid of the unnecessarily complicated SProc*
machinery. Later, all those swap*() calls will be replaced by macros.

dix: inline SProcPoly()
