X11Libre/xserver

- Xext/geext_priv.h
- Xext/panoramiXsrv.h
- Xext/xvdix.h
- dix/dix_priv.h
- dix/privates.c
- hw/xfree86/dri/dristruct.h
- hw/xfree86/modes/xf86Crtc.h
- include/privates.h
- miext/damage/damagestr.h
- miext/shadow/shadow.h
- os/client_priv.h
- randr/randrstr.h
- randr/randrstr_priv.h
- randr/rrcrtc.c
- render/picturestr.h
the dummy pointers are a big ugly but i see no other way of doing it
> nvidia support

- meson_options.txt
missed by #113
this is what's returned to clients
> change vendor string to XLibre

- .github/workflows/build-xserver.yml
* also run on pull requests
* drop -Dxwayland=false
*
> .github: few more little cleanups

- glx/rensize.c
@metux, I think you'll like this commit.
> glx: fix correct sizeof GL unsigned int

- glamor/glamor_egl.c
Port https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/751 to xlibre
Fixes glamor with modesetting on nvidia
@metux thoughts?
> glamor: Use EGL_LINUX_DMA_BUF_EXT to create GBM bo EGLImages

- composite/compext.c
The code is easier to understand if variables are declared when they're needed first.
> compext: declare variables when needed

- xkb/XKBMAlloc.c
Rebased from https://github.com/X11Libre/xserver/pull/270
> xkb: XKBMAlloc.c Solve CodeQL Alert Potential use after double free

- Xext/shape.c
* consolidate reply struct declaration / initialization
* use x_rpcbuf_t for payload assembly
> shape: consolidate reply assembly via x_rpcbuf_t

- Xext/panoramiX.c
- Xext/panoramiXprocs.c
using the new rpcbuf for assembling payloads
> panoramix: use rpcbuf

- .github/workflows/tidy-up-auto.yml
Add nightly cron job for automatically cleaning up old workflow runs.
> .github: delete old workflows

- glamor/glamor_egl.c
Backport https://github.com/X11Libre/xserver/pull/373 to maint.
@metux @dec05eba @HaplessIdiot Thoughts?
> Glamor maint backport

- meson.build
> Fixed xserver version

- .github/scripts/mingw32/cross-i686-w64-mingw32.txt
- .github/scripts/mingw32/cross-prereqs-build.sh
- .github/workflows/build-xserver.yml
* add mingw build to gitlab CI
* lots of mingw specific build fixes
*
> CI: add windows / mingw support

- hw/xfree86/common/xf86Init.c
- hw/xfree86/loader/loader.c
- hw/xfree86/loader/loader.h
- hw/xfree86/loader/loaderProcs.h
- hw/xfree86/loader/loadmod.c
Follow up for https://github.com/X11Libre/xserver/pull/494
@metux @dec05eba @HaplessIdiot @callmetango @ONykyf Thoughts?
> Warn when implicitly ignoring abi check on nvidia

- .github/scripts/mingw32/cross-prereqs-build.sh
- .github/workflows/build-xserver.yml
- hw/kdrive/ephyr/ephyr.c
- hw/kdrive/ephyr/hostx.c
- hw/kdrive/ephyr/meson.build
Fix Xephyr build on Windows and enable it in the github CI.
> .github: build xephyr on win32/mingw

- os/connection.c
It's such a cold and rarely used path, we really don't need writev() for efficiency, so instead doing two trivial write()'s. And the complex size calculation as well as extra padding isn't necessary, if we just make the string of size 4*n.
> os: connection: simplify connection error sending

- os/io.c
remove some redundancy in the error path
> os: io: FlushClient() consolidate error/abort code path

- os/Xtrans.c
- os/Xtrans.h
- os/Xtranssock.c
- os/Xtransutil.c
- os/meson.build
- os/ossock.c
- os/ossock.h
- os/xdmcp.c
move out the OS specific socket function logic into a separate "ossock" layer.
> os: cross platform socket function wrapper

- os/io.c
FlushClient() does drops the output buffer, when it becomes empty. This previously wasn't any problem and actually intented, because we've returned from the write path directly after FlushClient() was called.
But now we've changed the call order, so it's called from within OutputBufferMakeRoom(), so we need to make sure we always got valid output buffer before trying to access it.
For the future, we should think about whether dropping output buffers really makes sense at all. Instead we could leave them as they are (over the client's lifetime) and maybe just trim when they've went too big.
> os: io: fix NULL output buffer after FlushClient()

- composite/compinit.c
- exa/exa_glyphs.c
- exa/exa_render.c
- glamor/glamor.c
- glamor/glamor_composite_glyphs.c
- glamor/glamor_picture.c
- glamor/glamor_priv.h
- glamor/glamor_render.c
- glamor/glamor_trapezoid.c
- hw/kdrive/ephyr/ephyrcursor.c
- mi/midispcur.c
- render/picture.c
- render/render.c
yet another round of PICT_* to PIXMAN_* transition.
> replace PICT_* format identifiers by PIXMAN_* ones

- randr/rrproviderproperty.c
> randr: use x_rpcbuf_t in ProcRRGetProviderProperty()

- dix/property.c
> dix: use x_rpcbuf_t in ProcGetProperty()

- xkb/xkb.c
Use x_rpcbuf_t for assembling and byte-swapping the payload chunk.
> xkb: use x_rpcbuf_t in XkbWriteGeomOverlay()

- xkb/xkb.c
Use x_rpcbuf_t for reply payload chunk assembly and byte-swapping.
> xkb: XkbWriteGeomDoodads(): use x_rpcbuf_t

- Xi/xiproperty.c
Fixes: https://github.com/X11Libre/xserver/issues/670
> Xi: Fix xinput property count

- Xi/chgdctl.c
- Xi/getfocus.c
- Xi/getvers.c
- Xi/grabdev.c
- Xi/setbmap.c
- Xi/setdval.c
- Xi/setmmap.c
- Xi/setmode.c
- Xi/xigetclientpointer.c
- Xi/xigrabdev.c
- Xi/xiqueryversion.c
- Xi/xisetdevfocus.c
> Xi: xtest: use X_SEND_REPLY_SIMPLE()

- hw/kdrive/ephyr/ephyr.c
- hw/kdrive/src/kdrive.c
- hw/kdrive/src/kdrive.h
- hw/kdrive/src/kinput.c
- hw/kdrive/src/kmode.c
- hw/kdrive/src/meson.build
After this, all that is left to add is the drivers, the build system code, and the server code.
@metux thoughts?
> Kdrive ports for xfbdev

- Xext/security.c
Use x_rpcbuf_t for reply payload and X_SEND_REPLY_WITH_RPCBUF()
> Xext: security: use x_rpcbuf_t for reply payload assembly

- .github/scripts/mingw32/cross-prereqs-build.sh
The mingw32 build job often fails due frequent temporary problems on
cloning vom savannah. Retry several times, hoping to fix it.
> .github: win32: several retries on git clones

- Xext/xres.c
been using the wrong index for retrieving the resource type atom.
> Xext: xres: fix XResQueryClientResources request

- Xi/xiquerydevice.c
> Xi: ProcXIQueryDevice(): use x_rpcbuf_t

- Xi/queryst.c
> Xi: ProcXQueryDeviceState(): use x_rpcbuf_t

- Xi/getbmap.c
> Xi: ProcXGetDeviceButtonMapping(): use x_rpcbuf_t

- Xi/getmmap.c
> Xi: ProcXGetDeviceModifierMapping(): use x_rpcbuf_t

- Xi/gtmotion.c
> Xi: ProcXGetDeviceMotionEvents(): use x_rpcbuf_t

- Xi/getfctl.c
> Xi: ProcXGetFeedbackControl(): use x_rpcbuf_t

- Xi/xipassivegrab.c
> Xi: ProcXIPassiveGrabDevice(): use x_rpcbuf_t

- dix/devices.c
Use x_rpcbuf_t for reply payload assembly, so we can uniformly use the
X_SEND_REPLY_WITH_RPCBUF() macro for final write out.
> dix: devices: use x_rpcbuf_t for payload assembly

- xkb/xkb.c
At this point just use it as allocator, so we can use the
X_SEND_REPLY_WITH_RPCBUF() macro for final sending.
Follow-up commits will change the whole call stack to operate on
x_rpcbuf_t directly, so it's also doing the byte-swap for us.
> xkb: ProcXkbGetDeviceInfo(): use x_rpcbuf_t for reply payload assembly

- Xi/getdctl.c
Use x_rpcbuf_t also for writing individual fields and so let it also
do the byte-swapping.
> Xi: ProcXGetDeviceControl() also use x_rpcbuf_t for byte-swapping

- record/record.c
> record: use X_SEND_REPLY_SIMPLE() for simple replies

- Xi/listdev.c
> Xi: ProcXListInputDevices(): use x_rpcbuf_t

- Xi/xiallowev.c
The Xi protocol has some pretty unclean design aspect: instead of adding a
new sub-request type, version 2.2 introduced a different request structure
with some extra fields. So depending on which version the client has selected,
we need to operate on separate structs.
In the current implementation, there's a unclean hack by using the extended
structure and only accessing the extra fields when using v2.2 or above.
Even though this works, it's making the code unnecessarily complicated and
blocking the use if canonical request parsing macros (which are coming with
subsequent commits).
Thus, it's time to clean it up and only use the exactly correct structs
in the two different cases. The trick is just branching by version and pick
out the the interesting values from the corresponding structs, …
> Xi: ProcXIAllowEvents(): untwist request header handling

- Xext/xres.c
> Xext: xres: use x_rpcbuf_t

- hw/xfree86/common/xf86DGA.c
Use the X_SEND_REPLY_SIMPLE() macro for simple replies.
> xfree86: dga: use X_SEND_REPLY_SIMPLE() for simple replies

- randr/rrprovider.c
> randr: ProcRRGetProviderInfo(): use x_rpcbuf_t

- randr/rrscreen.c
> randr: rrGetMultiScreenResources(): use x_rpcbuf_t

- randr/rrscreen.c
> randr: rrGetScreenResources(): use x_rpcbuf_t

- render/render.c
Use x_rpcbuf_t for reply payload assembly and X_SEND_REPLY_WITH_RPCBUF()
> render: ProcRenderQueryPictIndexValues(): use x_rpcbuf_t

- hw/xquartz/applewm.c
- hw/xquartz/xpr/appledri.c
> xquartz: dri: use X_SEND_REPLY_SIMPLE() for simple replies

- Xext/dpms.c
The few instructions for byte-swapping are trivial enought to be inlined
into the actual request handlers, so we can reduce a lot of boilerplate.
> Xext: dpms: inline the SProc's

- dix/dispatch.c
> dix: ProcListInstalledColormaps(): use x_rpcbuf_t

- render/filter.c
> render: SetPictureFilter() declare and assign pScreenFilter in one shot

- dix/events.c
> dix: XineramaConstrainCursor(): assign and declara variables in one shot

- dri3/dri3_request.c
> dri3: proc_dri3_get_supported_modifiers(): use x_rpcbuf_t

- glx/glxcmds.c
- glx/glxcmdsswap.c
- glx/render2swap.c
- glx/renderpixswap.c
- glx/single2.c
- glx/single2swap.c
- glx/singlepixswap.c
- glx/unpack.h
We have an optimized function for this, so use it.
> glx: replace __GLX_SWAP_INT() by swapl()

- dix/dispatch.c
> dix: ProcAllocColorCells(): use x_rpcbuf_t

- render/render.c
make the variable's it easier to understand.
> render: ProcRenderAddGlyphs(): move locally used variables into local scope

- glx/indirect_util.c
> glx: __glXSendReply(): use x_rpcbuf_t

- Xext/saver.c
It's so trivial that those few lines can easily be inlined into
the actual request handler.
> Xext: saver: inline request swapping

- dix/enterleave.c
* make the code easier to read
* preparation for moving the looping into lambda-esque macros
(the code inside the loops doesn't compile in here, but does when
moved to separate functions)
> dix: enterleave: split out big looped code into separate functions

- hw/xfree86/common/xf86DGA.c
Simply do the action on matched screen inside the loop instead of
saving the found client and acting on it later (if found).
> xfree86: dga: simplify DGAClientStateChange()

- exa/exa_render.c
small and stupid change attempting to make the code cleaner and modern.
> exa: exaOpReadsDestination(): Updated switch case formatting

- Xi/exglobals.h
- Xi/xiallowev.c
- Xi/xiquerydevice.c
- Xi/xiquerypointer.c
- Xi/xiqueryversion.c
- dix/events.c
- test/xi2/protocol-xiqueryversion.c
> Xi: helper for private structure retrieval

- Xext/xvdisp.c
See: https://github.com/X11Libre/xserver/pull/1021
See: https://github.com/X11Libre/xserver/issues/706
> Xext: add __size_assert in xvdisp.c

- hw/xfree86/drivers/video/modesetting/drmmode_display.c
Split from https://github.com/X11Libre/xserver/pull/840
> modesetting: fix edge cases in cursor size calculations

- glx/glxcmds.c
- glx/vndcmds.c
> glx: Xi: use return value of X_SEND_REPLY_SIMPLE()

- Xext/bigreq.c
- Xext/damage/damageext.c
- Xext/dpms.c
- Xext/geext.c
- Xext/panoramiX.c
- Xext/panoramiXprocs.c
- Xext/saver.c
- Xext/security.c
- Xext/shape.c
- Xext/shm.c
- Xext/sync.c
- Xext/vidmode.c
- Xext/xcmisc.c
- Xext/xres.c
- Xext/xvmc.c
> Xext: Xi: use return value of X_SEND_REPLY_SIMPLE()

- composite/compext.c
- composite/meson.build
> compext: replace tabs by whitespaces

- render/render.c
> render: consolidate byte-swapping in ProcRenderCreatePicture()

- os/Xtranssock.c
> ../os/Xtranssock.c:494:5: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
>  494 |     strncpy(addr->sa_data, port, portlen);
>      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../os/Xtranssock.c:446:15: note: length computed here
>  446 |     portlen = strlen(port) + 1; // include space for trailing null
>      |               ^~~~~~~~~~~~
Since we already know the string length, we can just use memcpy()
> os: Xtranssock: fix warning on strncpy() call

- hw/xwin/dri/windowsdri.c
No need for having extra functions and redundant code when it can
be done with just few LoC.
> xwin: dri: inline byte-swapping

- Xext/xres.c
No need to have a hole bunch of extra functions, if we can just easily
inline the few relevant lines.
> Xext: xres: inline SProc*()'s

- render/render.c
> render: consolidate byte-swapping in ProcRenderTriangles()
